name: Pawel Stefanski
markdown: kramdown
 Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Poole
tagline:             The Jekyll Butler
url:                 http://getpoole.com
paginate:            1
baseurl:             ""
